// Auto-generated enums from Prisma schema
// Last updated: 2025-11-03

export enum MaterialStatus {
  Active = "Active",
  EndOfLife = "EndOfLife",
  Discontinue = "Discontinue",
}

export enum MaterialLocation {
  Local = "Local",
  Import = "Import",
}

export enum Components {
  Main_Equipment = "Main_Equipment",
  Supporting_Equipment = "Supporting_Equipment",
  Installation_Material = "Installation_Material",
  Consumables = "Consumables",
}

export enum ServiceUnit {
  Jam = "Jam",
  Hari = "Hari",
}

export enum SBU {
  IOT_AUTOMATION = "IOT_AUTOMATION",
  IT_CONSULTANCY = "IT_CONSULTANCY",
  IT_INFRASTRUCTURE = "IT_INFRASTRUCTURE",
  MEP = "MEP",
}

export enum KategoriSistem {
  DATA_CENTER_FACILITIES = "DATA_CENTER_FACILITIES",
  ELECTRICAL_SYSTEMS = "ELECTRICAL_SYSTEMS",
  FIRE_PROTECTION = "FIRE_PROTECTION",
  HVAC = "HVAC",
  INDUSTRIAL_AUTOMATION_SYSTEMS = "INDUSTRIAL_AUTOMATION_SYSTEMS",
  INTEGRATED_SMART_SOLUTIONS = "INTEGRATED_SMART_SOLUTIONS",
  IOT_SYSTEMS = "IOT_SYSTEMS",
  IT_MANAGEMENT_OPERATIONS_SOFTWARE = "IT_MANAGEMENT_OPERATIONS_SOFTWARE",
  IT_SERVICES = "IT_SERVICES",
  NETWORK_SECURITY = "NETWORK_SECURITY",
  PLUMBING_SYSTEMS = "PLUMBING_SYSTEMS",
  PROCESS_PIPING = "PROCESS_PIPING",
  SERVER_STORAGE = "SERVER_STORAGE",
}

export enum SubSistem {
  AC_SPLIT_SYSTEM = "AC_SPLIT_SYSTEM",
  BACKUP_DISASTER_RECOVERY = "BACKUP_DISASTER_RECOVERY",
  CENTRAL_CHILLER_SYSTEM = "CENTRAL_CHILLER_SYSTEM",
  CONVENTIONAL_POWER_SUPPLY_DISTRIBUTION = "CONVENTIONAL_POWER_SUPPLY_DISTRIBUTION",
  COOLING_INFRASTRUCTURE = "COOLING_INFRASTRUCTURE",
  CYBERSECURITY_SERVICES = "CYBERSECURITY_SERVICES",
  DIGITAL_TRANSFORMATION_SERVICES = "DIGITAL_TRANSFORMATION_SERVICES",
  FIELD_CONTROL_PLC_HMI = "FIELD_CONTROL_PLC_HMI",
  FIRE_ALARM_SYSTEM = "FIRE_ALARM_SYSTEM",
  GASEOUS_SYSTEM = "GASEOUS_SYSTEM",
  HYDRANT_SYSTEM = "HYDRANT_SYSTEM",
  INDUSTRIAL_NETWORKS = "INDUSTRIAL_NETWORKS",
  IOT_CONNECTIVITY_PLATFORMS = "IOT_CONNECTIVITY_PLATFORMS",
  IOT_EDGE_GATEWAY = "IOT_EDGE_GATEWAY",
  IOT_SENSORS_DEVICES = "IOT_SENSORS_DEVICES",
  IT_CONSULTING = "IT_CONSULTING",
  IT_OPERATIONS_AUTOMATION = "IT_OPERATIONS_AUTOMATION",
  LIGHTING_SYSTEM = "LIGHTING_SYSTEM",
  LOW_VOLTAGE_ACCESS_CONTROL_SYSTEM = "LOW_VOLTAGE_ACCESS_CONTROL_SYSTEM",
  LOW_VOLTAGE_BAS_BMS_CABLING = "LOW_VOLTAGE_BAS_BMS_CABLING",
  LOW_VOLTAGE_CCTV_SYSTEM = "LOW_VOLTAGE_CCTV_SYSTEM",
  LOW_VOLTAGE_MATV = "LOW_VOLTAGE_MATV",
  LOW_VOLTAGE_NETWORK_CABLING_SYSTEM = "LOW_VOLTAGE_NETWORK_CABLING_SYSTEM",
  LOW_VOLTAGE_PABX_SYSTEM = "LOW_VOLTAGE_PABX_SYSTEM",
  LOW_VOLTAGE_PUBLIC_ADDRESS_SYSTEM = "LOW_VOLTAGE_PUBLIC_ADDRESS_SYSTEM",
  MANAGED_IT_SERVICES = "MANAGED_IT_SERVICES",
  MANUFACTURING_EXECUTION_SYSTEM_MES = "MANUFACTURING_EXECUTION_SYSTEM_MES",
  MOTION_CONTROL_DRIVES = "MOTION_CONTROL_DRIVES",
  NETWORK_INFRASTRUCTURE = "NETWORK_INFRASTRUCTURE",
  NETWORK_MANAGEMENT_MONITORING = "NETWORK_MANAGEMENT_MONITORING",
  NETWORK_SECURITY = "NETWORK_SECURITY",
  PHYSICAL_INFRASTRUCTURE = "PHYSICAL_INFRASTRUCTURE",
  PIPA_CAIRAN_PROSES_KIMIA = "PIPA_CAIRAN_PROSES_KIMIA",
  PIPA_GAS_UDARA_BERTEKANAN = "PIPA_GAS_UDARA_BERTEKANAN",
  PIPA_UTILITAS_UMUM = "PIPA_UTILITAS_UMUM",
  POWER_INFRASTRUCTURE = "POWER_INFRASTRUCTURE",
  RENEWABLE_ENERGY_SYSTEM = "RENEWABLE_ENERGY_SYSTEM",
  ROBOTICS = "ROBOTICS",
  SERVER_INFRASTRUCTURE = "SERVER_INFRASTRUCTURE",
  SMART_AGRICULTURE_PRECISION_FARMING = "SMART_AGRICULTURE_PRECISION_FARMING",
  SMART_BUILDING = "SMART_BUILDING",
  SMART_CITY_SOLUTIONS = "SMART_CITY_SOLUTIONS",
  SMART_ENERGY_GRID_MANAGEMENT = "SMART_ENERGY_GRID_MANAGEMENT",
  SMART_HEALTHCARE_SOLUTIONS = "SMART_HEALTHCARE_SOLUTIONS",
  SMART_LOGISTICS_SUPPLY_CHAIN = "SMART_LOGISTICS_SUPPLY_CHAIN",
  SMART_MANUFACTURING = "SMART_MANUFACTURING",
  SMART_RETAIL_SOLUTIONS = "SMART_RETAIL_SOLUTIONS",
  SPRINKLER_SYSTEM = "SPRINKLER_SYSTEM",
  STORAGE_SYSTEMS = "STORAGE_SYSTEMS",
  SUPERVISORY_CONTROL_SCADA_DCS = "SUPERVISORY_CONTROL_SCADA_DCS",
  VENTILATION_SYSTEM = "VENTILATION_SYSTEM",
  VIRTUALIZATION_CONTAINERIZATION = "VIRTUALIZATION_CONTAINERIZATION",
  VRV_VRF_SYSTEM = "VRV_VRF_SYSTEM",
  WASTE_DRAINAGE_SYSTEM = "WASTE_DRAINAGE_SYSTEM",
  WATER_SUPPLY_SYSTEM = "WATER_SUPPLY_SYSTEM",
}

export enum FaseProyek {
  PASCA_PROYEK = "PASCA_PROYEK",
  PRA_PROYEK = "PRA_PROYEK",
  SAAT_PROYEK = "SAAT_PROYEK",
}

export enum KategoriJasa {
  ADMINISTRASI_DOKUMENTASI = "ADMINISTRASI_DOKUMENTASI",
  AKUISISI_PEMROSESAN_DATA = "AKUISISI_PEMROSESAN_DATA",
  ANALISIS_ASESMEN = "ANALISIS_ASESMEN",
  ANALISIS_DESAIN = "ANALISIS_DESAIN",
  ANALISIS_KONSULTASI = "ANALISIS_KONSULTASI",
  ASESMEN_PENGUJIAN = "ASESMEN_PENGUJIAN",
  DESAIN_ANALISIS = "DESAIN_ANALISIS",
  DESAIN_ARSITEKTUR = "DESAIN_ARSITEKTUR",
  DESAIN_ASESMEN = "DESAIN_ASESMEN",
  DESAIN_ENGINEERING = "DESAIN_ENGINEERING",
  DOKUMENTASI_HANDOVER = "DOKUMENTASI_HANDOVER",
  DUKUNGAN = "DUKUNGAN",
  DUKUNGAN_ADOPSI = "DUKUNGAN_ADOPSI",
  DUKUNGAN_OPTIMISASI = "DUKUNGAN_OPTIMISASI",
  DUKUNGAN_PEMELIHARAAN = "DUKUNGAN_PEMELIHARAAN",
  DUKUNGAN_PENGEMBANGAN = "DUKUNGAN_PENGEMBANGAN",
  DUKUNGAN_PERBAIKAN = "DUKUNGAN_PERBAIKAN",
  EDUKASI = "EDUKASI",
  ENGAGEMENT_DISCOVERY = "ENGAGEMENT_DISCOVERY",
  FABRIKASI_INSTALASI = "FABRIKASI_INSTALASI",
  IMPLEMENTASI = "IMPLEMENTASI",
  IMPLEMENTASI_INSTALASI = "IMPLEMENTASI_INSTALASI",
  IMPLEMENTASI_INTEGRASI = "IMPLEMENTASI_INTEGRASI",
  IMPLEMENTASI_KONFIGURASI = "IMPLEMENTASI_KONFIGURASI",
  IMPLEMENTASI_PERBAIKAN = "IMPLEMENTASI_PERBAIKAN",
  IMPLEMENTASI_CLOUD = "IMPLEMENTASI_CLOUD",
  INSTALASI = "INSTALASI",
  INSTALASI_FISIK = "INSTALASI_FISIK",
  INTEGRASI = "INTEGRASI",
  INTEGRASI_TEKNOLOGI = "INTEGRASI_TEKNOLOGI",
  KONFIGURASI = "KONFIGURASI",
  KONFIGURASI_PENGEMBANGAN = "KONFIGURASI_PENGEMBANGAN",
  KUALITAS_DEPLOYMENT = "KUALITAS_DEPLOYMENT",
  LAYANAN = "LAYANAN",
  LAYANAN_DUKUNGAN = "LAYANAN_DUKUNGAN",
  LAYANAN_BERKELANJUTAN = "LAYANAN_BERKELANJUTAN",
  LAYANAN_DUKUNGAN_SUPPORT = "LAYANAN_DUKUNGAN_SUPPORT",
  LAYANAN_TERKELOLA = "LAYANAN_TERKELOLA",
  LOGISTIK_RIGGING = "LOGISTIK_RIGGING",
  MANAJEMEN = "MANAJEMEN",
  MANAJEMEN_INFRASTRUKTUR = "MANAJEMEN_INFRASTRUKTUR",
  MANAJEMEN_PROYEK = "MANAJEMEN_PROYEK",
  MIGRASI = "MIGRASI",
  ONBOARDING_TRANSISI = "ONBOARDING_TRANSISI",
  PELAPORAN_REVIEW = "PELAPORAN_REVIEW",
  PEMELIHARAAN = "PEMELIHARAAN",
  PEMELIHARAAN_DUKUNGAN = "PEMELIHARAAN_DUKUNGAN",
  PENGEMBANGAN = "PENGEMBANGAN",
  PENGEMBANGAN_INTEGRASI = "PENGEMBANGAN_INTEGRASI",
  PENGEMBANGAN_SOFTWARE = "PENGEMBANGAN_SOFTWARE",
  PENYAMPAIAN = "PENYAMPAIAN",
  SALES_KONSULTASI_AWAL = "SALES_KONSULTASI_AWAL",
  SALES_SCOPING = "SALES_SCOPING",
  STRATEGI_PERENCANAAN = "STRATEGI_PERENCANAAN",
  SURVEY_DESAIN = "SURVEY_DESAIN",
  T_AND_C = "T_AND_C",
}

export enum ProjectStatus {
  PLANNING = "PLANNING",
  IN_PROGRESS = "IN_PROGRESS",
  ON_HOLD = "ON_HOLD",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
}

export enum EstimationStatus {
  DRAFT = "DRAFT",
  SUBMITTED = "SUBMITTED",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
}

export enum ItemType {
  MATERIAL = "MATERIAL",
  SERVICE = "SERVICE",
}

export enum SourceType {
  VENDOR = "VENDOR",
  INTERNAL = "INTERNAL",
}

export enum MilestoneStatus {
  PENDING = "PENDING",
  IN_PROGRESS = "IN_PROGRESS",
  COMPLETED = "COMPLETED",
}

// Helper functions for enum conversions
export const enumToOptions = <T extends Record<string, string>>(
  enumObj: T,
): { value: string; label: string }[] => {
  return Object.values(enumObj).map((value) => ({
    value,
    label: value.replace(/_/g, " "),
  }));
};

export const enumToArray = <T extends Record<string, string>>(enumObj: T): string[] => {
  return Object.values(enumObj);
};
